image:
  file: .gitpod.Dockerfile
tasks:
  - init: >
      chmod +x envconfig.sh &&
      ./envconfig.sh
  - command: >
      export CMAKE_PREFIX=/opt/conda

vscode:
  extensions:
    - gocarlos.cmake-tools@1.5.2:nUO/opvJVLgFgKq+tbOX6A==
    - ms-vscode.cpptools@0.26.2:Pq/tmf2WN3SanVzB4xZc1g==
