ports:
- port: 8050
  onOpen: open-preview
- port: 8888
  onOpen: open-browser
image:
  file: .gitpod.Dockerfile
tasks:
  - init: >
      chmod +x envconfig.sh &&
      ./envconfig.sh
  - command: >
      export CMAKE_PREFIX=/opt/conda

vscode:
  extensions:
    - ms-vscode.cpptools@0.26.2:Pq/tmf2WN3SanVzB4xZc1g==
    - cschlosser.doxdocgen@0.5.2:SsSNhKMGwp5iVRhI1fnHVA==
    - ms-vscode.cmake-tools@1.4.2:85XiRZZTNCh6JgvEqefqww==
