name: ellcpp
channels:
  - conda-forge
dependencies:
  # - cmake
  - nlohmann_json
  - fmt
  - spdlog
  - boost
  - doctest
  - benchmark
  - openblas
  - fftw
  - xtensor
  - xtensor-blas
  - xtensor-fftw
